empty: empty.cpp
	g++ empty.cpp -o empty && ./empty
empty_size: empty_size.cpp
	g++ empty_size.cpp -o empty_size && ./empty_size
implicit_empty: implicit_empty.cpp
	g++ implicit_empty.cpp -o implicit_empty && ./implicit_empty
namedobject: namedobject.cpp
	g++ namedobject.cpp -o namedobject && ./namedobject
clean:
	rm -rf empty empty_size implicit_empty namedobject a.out
	
