homeacc: homeacc.cpp logger.h logger.cpp
	rm -f homeacc.out
	g++ -o homeacc.out homeacc.cpp logger.h logger.cpp -std=c++11
	./homeacc.out
mainlogger: mainlogger.cpp logger.h logger.cpp
	rm -f mainlogger.out
	g++ -Wfatal-errors -o mainlogger.out mainlogger.cpp logger.h logger.cpp -std=c++11
	./mainlogger.out
