const_versatility: const_versatility.cpp
	g++ const_versatility.cpp -o const_versatility && ./const_versatility
const_template_param: const_template_param.cpp
	g++ const_template_param.cpp -o const_template_param && ./const_template_param
const_vector_iter: const_vector_iter.cpp
	g++ -Wfatal-errors const_vector_iter.cpp -o const_vector_iter && ./const_vector_iter
return_const_object: return_const_object.cpp
	g++ return_const_object.cpp -o return_const_object && ./return_const_object
const_method: const_method.cpp
	g++ const_method.cpp -o const_method && ./const_method
modify_return_value: modify_return_value.cpp
	g++ modify_return_value.cpp -o modify_return_value && ./modify_return_value
constancy: constancy.cpp
	g++ -Wfatal-errors constancy.cpp -o constancy && ./constancy
clean:
	rm -f *.exe *.o
no_logical_constancy: no_logical_constancy.cpp
	g++ -Wfatal-errors no_logical_constancy.cpp -o no_logical_constancy && ./no_logical_constancy
