ref_init: reference_init.cpp
	g++ reference_init.cpp -o ref_init && ./ref_init
clean:
	rm -f ref_init many_constr
many_constr: many_constructors.cpp
	g++ many_constructors.cpp -o many_constr && ./many_constr
